Partie 1 – Series 
1) Créer une Series contenant 4 températures  
2) Afficher son index 
3) Afficher la 1ère valeur 
4) Afficher la dernière valeur 
5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de 
mesure 12h, 13h, 14h et 15h 
6) Afficher la 1ère et la dernière valeur

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\rokha\miniconda3\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\rokha\miniconda3\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\rokha\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\rokha\miniconda3\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\rokha\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [34]:
%pip install numpy

Requirement already satisfied: numpy in c:\Users\rokha\miniconda3\Lib\site-packages (2.5.2)
Note: you may need to restart the kernel to use updated packages.

In [35]:
import numpy as np

1.Créer une series contenant 4 temperatures

In [4]:
temperatures = pd.Series([15, 28, 32, 44, 35])
print(temperatures)

0    15
1    28
2    32
3    44
4    35
dtype: int64

2.Afficher son index

In [5]:
print(temperatures.index)

RangeIndex(start=0, stop=5, step=1)

3.Afficher la 1ère valeur

In [6]:
print(temperatures.iloc[0])

15

4.Afficher la dernière valeur

In [7]:
print(temperatures.iloc[-1])

35

Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de 
mesure 12h, 13h, 14h et 15h

In [8]:
temperatures_heures = pd.Series(
    [24.5, 25.3, 26.1, 27.4],
    index=["12h", "13h", "14h", "15h"]
)

print(temperatures_heures)

12h    24.5
13h    25.3
14h    26.1
15h    27.4
dtype: float64

In [9]:
temperatures_heures = pd.Series([24.5, 25.3, 26.1, 27.4])

temperatures_heures.index = ["12h", "13h", "14h", "15h"]

print(temperatures_heures)

12h    24.5
13h    25.3
14h    26.1
15h    27.4
dtype: float64

6.Afficher la 1ère et la dernière valeur

In [10]:
print("Première valeur :", temperatures_heures.iloc[0])
print("Dernière valeur :", temperatures_heures.iloc[-1])

Première valeur : 24.5
Dernière valeur : 27.4

Partie 2 – DataFrame 
1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant 
data = { 
"capteur": ["C001", "C002", "C003"], 
"temperature": [24.5, 25.1, 26.3], 
"humidite": [65, 67, 70] 
} 
2) Importer le dataset mesures_capteurs.csv dans le dataframe df 
3) Afficher les dimensions de df 
NB : dans la suite de l’atelier, on travaillera avec le dataframe df

1.Créer et afficher le dataframe df_test à partir du dictionnaire suivant 
data = { 
"capteur": ["C001", "C002", "C003"], 
"temperature": [24.5, 25.1, 26.3], 
"humidite": [65, 67, 70] }

In [11]:
data = { 
"capteur": ["C001", "C002", "C003"], 
"temperature": [24.5, 25.1, 26.3], 
"humidite": [65, 67, 70] 
}
df_test = pd.DataFrame(data)

print(df_test)

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

2.Importer le dataset mesures_capteurs.csv dans le dataframe df

In [12]:
df = pd.read_csv("../data/mesures_capteurs.csv")

print(df)

    id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0       M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1       M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2       M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3       M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4       M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80
..        ...                  ...        ...      ...          ...       ...
600     M0072  2026-01-07 23:00:00       C012     B004        23.67     60.28
601     M0107  2026-01-09 10:00:00       C011     B004        24.34     61.42
602     M0271  2026-01-16 06:00:00       C007     B003        23.73     63.49
603     M0436  2026-01-23 03:00:00       C004     B002        24.83     79.77
604     M0103  2026-01-09 06:00:00       C007     B003        17.02     52.04

     pression  consommation etat
0     1008.95        287.28   OK
1      993.39        116.20   OK
2     1010.32        288.50   OK
3     1019.62        136.65   OK
4     1016.58        182.62   OK
..        ...           ...  ...
600   1015.11        282.36   OK
601   1019.43        357.43   OK
602   1016.46        152.79   OK
603   1017.05        170.97   OK
604   1001.14         44.99   OK

[605 rows x 9 columns]

3.Afficher les dimensions de df 
NB : dans la suite de l’atelier, on travaillera avec le dataframe df

In [13]:
dimensions = df.shape
print("Dimensions du DataFrame :", dimensions)

Dimensions du DataFrame : (605, 9)

Partie 3 – Exploration 
1) Afficher les premières lignes 
2) Afficher les 10 premières lignes 
3) Afficher les dernières lignes 
4) Afficher le nombre de lignes 
5) Afficher le nombre de colonnes 
6) Afficher les noms des colonnes 
7) Afficher les informations générales 
8) Afficher les statistiques descriptives

1.Afficher les premières lignes

In [14]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

2. Afficher les 10 premières lignes

In [15]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

3.Afficher les dernières lignes

In [16]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

4.Afficher le nombre de lignes

In [24]:
print(df.shape[0])

605

5.Afficher le nombre de colonnes

In [25]:
print(df.shape[1])

9

6.Afficher les noms des colonnes

In [26]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='str')

7.Afficher les informations générales

In [27]:
df.info

<bound method DataFrame.info of     id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0       M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1       M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2       M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3       M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4       M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80
..        ...                  ...        ...      ...          ...       ...
600     M0072  2026-01-07 23:00:00       C012     B004        23.67     60.28
601     M0107  2026-01-09 10:00:00       C011     B004        24.34     61.42
602     M0271  2026-01-16 06:00:00       C007     B003        23.73     63.49
603     M0436  2026-01-23 03:00:00       C004     B002        24.83     79.77
604     M0103  2026-01-09 06:00:00       C007     B003        17.02     52.04

     pression  consommation etat
0     1008.95        287.28   OK
1      993.39        116.20   OK
2     1010.32        288.50   OK
3     1019.62        136.65   OK
4     1016.58        182.62   OK
..        ...           ...  ...
600   1015.11        282.36   OK
601   1019.43        357.43   OK
602   1016.46        152.79   OK
603   1017.05        170.97   OK
604   1001.14         44.99   OK

[605 rows x 9 columns]>

8.Afficher les statistiques descriptives

In [28]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

Partie 4 – Sélection  
1) Sélectionner la colonne "temperature" 
2) Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"  
3) Sélectionner les 5 premières lignes avec loc 
4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

1.Selectionner la colonne "temperature"

In [29]:
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

2.Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"

In [30]:
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

3.Sélectionner les 5 premières lignes avec loc

In [31]:
df.loc[:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

4. Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

In [32]:
df.iloc[:5, :4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

Partie 5 – Manipulation des colonnes 
1) Ajouter la colonne "temperature_fahrenheit" 
2) Ajouter la colonne "niveau_temperature" pour catégoriser la température en  
"Élevée" (température> 30) ou "Normale". On peut utiliser la méthode where() de numpy 
3) Renommer la colonne "humidite" en "humidite_relative" 
4) Supprimer la colonne "temperature_fahrenheit"

1.Ajouter la colonne "temperature_fahrenheit"

In [33]:
df["temperature_fahrenheit"] = df["temperature"] * 9/5 + 32

2. Ajouter la colonne "niveau_temperature" pour catégoriser la température en  
"Élevée" (température
 > 30) ou "Normale". On peut utiliser la méthode where() de numpy

In [36]:
df["niveau_temperature"] = np.where(
    df["temperature"] > 30,
    "Élevée",
    "Normale"
)

3.Renommer la colonne "humidite" en "humidite_relative"

In [37]:
df.rename(
    columns={"humidite": "humidite_relative"},
    inplace=True
)

4.Supprimer la colonne "temperature_fahrenheit"

In [38]:
df.drop(columns=["temperature_fahrenheit"], inplace=True)

Partie 6 – Filtrage 
1) Récupérer uniquement les lignes telles que température > 30 
2) Récupérer uniquement les lignes telles température > 30 et humidité > 70

1.Récupérer uniquement les lignes telles que température > 30

In [39]:
df_temperature_chaude = df[df["temperature"] > 30]

print(df_temperature_chaude)

    id_mesure           date_heure id_capteur batiment  temperature  \
7       M0132  2026-01-10 11:00:00       C012     B004        31.21
43      M0575  2026-01-28 22:00:00       C011     B004        34.72
47      M0082  2026-01-08 09:00:00       C010     B004        32.46
63      M0064  2026-01-07 15:00:00       C004     B002        31.19
79      M0275  2026-01-16 10:00:00       C011     B004        31.74
88      M0288  2026-01-16 23:00:00       C012     B004        30.06
103     M0311  2026-01-17 22:00:00       C011     B004        30.83
112     M0149  2026-01-11 04:00:00       C005     B002        31.46
118     M0365  2026-01-20 04:00:00       C005     B002        32.90
129     M0592  2026-01-29 15:00:00       C004     B002        33.60
137     M0076  2026-01-08 03:00:00       C004     B002        31.18
145     M0503  2026-01-25 22:00:00       C011     B004        30.57
146     M0118  2026-01-09 21:00:00       C010     B004        30.32
165     M0323  2026-01-18 10:00:00       C011     B004        33.01
168     M0276  2026-01-16 11:00:00       C012     B004        30.39
169     M0546  2026-01-27 17:00:00       C006     B002        32.36
174     M0405  2026-01-21 20:00:00       C009     B003        31.74
210     M0588  2026-01-29 11:00:00       C012     B004        31.51
211     M0370  2026-01-20 09:00:00       C010     B004        33.29
224     M0303  2026-01-17 14:00:00       C003     B001        30.84
243     M0416  2026-01-22 07:00:00       C008     B003        30.16
246     M0312  2026-01-17 23:00:00       C012     B004        30.13
251     M0114  2026-01-09 17:00:00       C006     B002        31.85
257     M0378  2026-01-20 17:00:00       C006     B002        31.99
264     M0191  2026-01-12 22:00:00       C011     B004        30.75
274     M0046  2026-01-06 21:00:00       C010     B004        30.92
280     M0585  2026-01-29 08:00:00       C009     B003        31.30
322     M0120  2026-01-09 23:00:00       C012     B004        30.19
356     M0574  2026-01-28 21:00:00       C010     B004        30.61
362     M0396  2026-01-21 11:00:00       C012     B004        30.57
385     M0126  2026-01-10 05:00:00       C006     B002        30.09
398     M0514  2026-01-26 09:00:00       C010     B004        30.48
401     M0586  2026-01-29 09:00:00       C010     B004        31.44
404     M0598  2026-01-29 21:00:00       C010     B004        30.37
417     M0432  2026-01-22 23:00:00       C012     B004        30.38
437     M0286  2026-01-16 21:00:00       C010     B004        32.16
438     M0558  2026-01-28 05:00:00       C006     B002        32.56
447     M0170  2026-01-12 01:00:00       C002     B001        31.15
488     M0431  2026-01-22 22:00:00       C011     B004        30.14
492     M0552  2026-01-27 23:00:00       C012     B004        30.24
500     M0062  2026-01-07 13:00:00       C002     B001        30.39
502     M0048  2026-01-06 23:00:00       C012     B004        58.70
505     M0268  2026-01-16 03:00:00       C004     B002        30.34
520     M0063  2026-01-07 14:00:00       C003     B001        32.72
541     M0202  2026-01-13 09:00:00       C010     B004        30.86
558     M0346  2026-01-19 09:00:00       C010     B004        30.68

     humidite_relative  pression  consommation    etat niveau_temperature
7                60.57   1024.64        285.92      OK             Élevée
43               57.50   1008.94        266.22  ALERTE             Élevée
47               72.31   1000.42        276.99  ALERTE             Élevée
63               55.13   1011.04        264.98      OK             Élevée
79               69.95   1020.79        335.89      OK             Élevée
88               75.30   1014.47        323.32      OK             Élevée
103              54.99   1026.47        256.11      OK             Élevée
112              48.48   1002.75        210.94      OK             Élevée
118              65.91   1027.28        246.08  ALERTE             Élevée
129              79.80   1021.96        212.55  ALERTE             Élevée
137              49.66   1019.91        215.22      OK             Élevée
145              71.26   1002.88        359.97      OK             Élevée
146                NaN   1015.78        261.68      OK             Élevée
165              73.24   1014.36        260.24  ALERTE             Élevée
168              71.14   1017.79        303.38      OK             Élevée
169              67.34    998.10        184.89  ALERTE             Élevée
174              47.23   1015.59        115.79      OK             Élevée
210              72.49   1018.21        307.97      OK             Élevée
211              50.43   1009.87        356.76  ALERTE             Élevée
224              67.98   1020.09        157.99      OK             Élevée
243              54.00   1012.18        875.00  ERREUR             Élevée
246              65.68   1009.70        198.65      OK             Élevée
251              85.77   1013.56        237.21  ALERTE             Élevée
257              66.32   1013.54        254.67      OK             Élevée
264              71.35   1018.92        308.66      OK             Élevée
274              67.19   1009.71        329.78      OK             Élevée
280              73.35   1021.40        187.98      OK             Élevée
322              53.58   1013.05        396.90  ALERTE             Élevée
356              60.73   1022.32        321.75      OK             Élevée
362              63.47   1017.40        248.36      OK             Élevée
385              73.95   1007.24        162.39      OK             Élevée
398              93.57   1015.93        306.24  ALERTE             Élevée
401              63.10    996.56        271.51      OK             Élevée
404              64.55    997.31        311.77      OK             Élevée
417              65.98   1005.48        256.18      OK             Élevée
437              41.80    996.99        255.56  ALERTE             Élevée
438              67.77   1016.88        181.51  ALERTE             Élevée
447              69.20   1016.10        172.49      OK             Élevée
488              51.02   1007.70        366.53  ALERTE             Élevée
492              62.06   1009.35        299.69      OK             Élevée
500              52.13   1004.23        262.66      OK             Élevée
502              81.51   1026.79        271.92  ERREUR             Élevée
505              64.23   1011.42        179.84      OK             Élevée
520              53.28   1010.05        195.37  ALERTE             Élevée
541              76.00   1011.94        224.01      OK             Élevée
558              36.33   1010.46        272.59      OK             Élevée

2.Récupérer uniquement les lignes telles température > 30 et humidité > 70

In [40]:
df_filtre = df[
    (df["temperature"] > 30) &
    (df["humidite_relative"] > 70)
]

print(df_filtre)

    id_mesure           date_heure id_capteur batiment  temperature  \
47      M0082  2026-01-08 09:00:00       C010     B004        32.46
88      M0288  2026-01-16 23:00:00       C012     B004        30.06
129     M0592  2026-01-29 15:00:00       C004     B002        33.60
145     M0503  2026-01-25 22:00:00       C011     B004        30.57
165     M0323  2026-01-18 10:00:00       C011     B004        33.01
168     M0276  2026-01-16 11:00:00       C012     B004        30.39
210     M0588  2026-01-29 11:00:00       C012     B004        31.51
251     M0114  2026-01-09 17:00:00       C006     B002        31.85
264     M0191  2026-01-12 22:00:00       C011     B004        30.75
280     M0585  2026-01-29 08:00:00       C009     B003        31.30
385     M0126  2026-01-10 05:00:00       C006     B002        30.09
398     M0514  2026-01-26 09:00:00       C010     B004        30.48
502     M0048  2026-01-06 23:00:00       C012     B004        58.70
541     M0202  2026-01-13 09:00:00       C010     B004        30.86

     humidite_relative  pression  consommation    etat niveau_temperature
47               72.31   1000.42        276.99  ALERTE             Élevée
88               75.30   1014.47        323.32      OK             Élevée
129              79.80   1021.96        212.55  ALERTE             Élevée
145              71.26   1002.88        359.97      OK             Élevée
165              73.24   1014.36        260.24  ALERTE             Élevée
168              71.14   1017.79        303.38      OK             Élevée
210              72.49   1018.21        307.97      OK             Élevée
251              85.77   1013.56        237.21  ALERTE             Élevée
264              71.35   1018.92        308.66      OK             Élevée
280              73.35   1021.40        187.98      OK             Élevée
385              73.95   1007.24        162.39      OK             Élevée
398              93.57   1015.93        306.24  ALERTE             Élevée
502              81.51   1026.79        271.92  ERREUR             Élevée
541              76.00   1011.94        224.01      OK             Élevée

Partie 7 : Tri 
1) Créer df_trie1 pour trier en fonction de la température croissante 
2) Créer df_trie2 pour trier en fonction de la température décroissante 
3) Créer top10 pour voir les 10 températures les plus élevées 
4) Trier en fonction des colonnes "batiment" (croissant) et "temperature" (décroissant)

1.Créer df_trie1 pour trier en fonction de la température croissante

In [41]:
df_trie1 = df.sort_values(by="temperature")

print(df_trie1)

    id_mesure           date_heure id_capteur batiment  temperature  \
487     M0538  2026-01-27 09:00:00       C010     B004       -18.50
245     M0127  2026-01-10 06:00:00       C007     B003        14.11
258     M0223  2026-01-14 06:00:00       C007     B003        15.49
249     M0175  2026-01-12 06:00:00       C007     B003        16.04
59      M0146  2026-01-11 01:00:00       C002     B001        16.77
..        ...                  ...        ...      ...          ...
163     M0019  2026-01-05 18:00:00       C007     B003          NaN
215     M0204  2026-01-13 11:00:00       C012     B004          NaN
513     M0490  2026-01-25 09:00:00       C010     B004          NaN
548     M0572  2026-01-28 19:00:00       C008     B003          NaN
556     M0092  2026-01-08 19:00:00       C008     B003          NaN

     humidite_relative  pression  consommation    etat niveau_temperature
487              66.27   1012.49        312.92  ERREUR            Normale
245             145.00   1032.36        169.57  ERREUR            Normale
258              47.96   1006.34        124.90      OK            Normale
249              55.36   1005.68        140.95      OK            Normale
59               53.44   1010.65        131.75      OK            Normale
..                 ...       ...           ...     ...                ...
163              69.97   1014.14        181.07      OK            Normale
215              59.96   1007.98        294.02      OK            Normale
513              52.97   1010.71        253.63      OK            Normale
548              68.63   1018.58        252.48      OK            Normale
556              79.81   1007.05        113.00      OK            Normale

[605 rows x 10 columns]

2.Créer df_trie2 pour trier en fonction de la température décroissante

In [42]:
df_trie2 = df.sort_values(
    by="temperature",
    ascending=False
)

print(df_trie2)

    id_mesure           date_heure id_capteur batiment  temperature  \
502     M0048  2026-01-06 23:00:00       C012     B004        58.70
43      M0575  2026-01-28 22:00:00       C011     B004        34.72
129     M0592  2026-01-29 15:00:00       C004     B002        33.60
211     M0370  2026-01-20 09:00:00       C010     B004        33.29
165     M0323  2026-01-18 10:00:00       C011     B004        33.01
..        ...                  ...        ...      ...          ...
163     M0019  2026-01-05 18:00:00       C007     B003          NaN
215     M0204  2026-01-13 11:00:00       C012     B004          NaN
513     M0490  2026-01-25 09:00:00       C010     B004          NaN
548     M0572  2026-01-28 19:00:00       C008     B003          NaN
556     M0092  2026-01-08 19:00:00       C008     B003          NaN

     humidite_relative  pression  consommation    etat niveau_temperature
502              81.51   1026.79        271.92  ERREUR             Élevée
43               57.50   1008.94        266.22  ALERTE             Élevée
129              79.80   1021.96        212.55  ALERTE             Élevée
211              50.43   1009.87        356.76  ALERTE             Élevée
165              73.24   1014.36        260.24  ALERTE             Élevée
..                 ...       ...           ...     ...                ...
163              69.97   1014.14        181.07      OK            Normale
215              59.96   1007.98        294.02      OK            Normale
513              52.97   1010.71        253.63      OK            Normale
548              68.63   1018.58        252.48      OK            Normale
556              79.81   1007.05        113.00      OK            Normale

[605 rows x 10 columns]

3.Créer top10 pour voir les 10 températures les plus élevées

In [43]:
top10 = df.sort_values(
    by="temperature",
    ascending=False
).head(10)

print(top10)

    id_mesure           date_heure id_capteur batiment  temperature  \
502     M0048  2026-01-06 23:00:00       C012     B004        58.70
43      M0575  2026-01-28 22:00:00       C011     B004        34.72
129     M0592  2026-01-29 15:00:00       C004     B002        33.60
211     M0370  2026-01-20 09:00:00       C010     B004        33.29
165     M0323  2026-01-18 10:00:00       C011     B004        33.01
118     M0365  2026-01-20 04:00:00       C005     B002        32.90
520     M0063  2026-01-07 14:00:00       C003     B001        32.72
438     M0558  2026-01-28 05:00:00       C006     B002        32.56
47      M0082  2026-01-08 09:00:00       C010     B004        32.46
169     M0546  2026-01-27 17:00:00       C006     B002        32.36

     humidite_relative  pression  consommation    etat niveau_temperature
502              81.51   1026.79        271.92  ERREUR             Élevée
43               57.50   1008.94        266.22  ALERTE             Élevée
129              79.80   1021.96        212.55  ALERTE             Élevée
211              50.43   1009.87        356.76  ALERTE             Élevée
165              73.24   1014.36        260.24  ALERTE             Élevée
118              65.91   1027.28        246.08  ALERTE             Élevée
520              53.28   1010.05        195.37  ALERTE             Élevée
438              67.77   1016.88        181.51  ALERTE             Élevée
47               72.31   1000.42        276.99  ALERTE             Élevée
169              67.34    998.10        184.89  ALERTE             Élevée

4.Trier en fonction des colonnes "batiment" (croissant) et "temperature" (décroissant)

In [44]:
df_trie = df.sort_values(
    by=["batiment", "temperature"],
    ascending=[True, False]
)

print(df_trie)

    id_mesure           date_heure id_capteur batiment  temperature  \
520     M0063  2026-01-07 14:00:00       C003     B001        32.72
447     M0170  2026-01-12 01:00:00       C002     B001        31.15
224     M0303  2026-01-17 14:00:00       C003     B001        30.84
500     M0062  2026-01-07 13:00:00       C002     B001        30.39
9       M0087  2026-01-08 14:00:00       C003     B001        28.85
..        ...                  ...        ...      ...          ...
277     M0383  2026-01-20 22:00:00       C011     B004        20.60
338     M0060  2026-01-07 11:00:00       C012     B004        20.56
487     M0538  2026-01-27 09:00:00       C010     B004       -18.50
215     M0204  2026-01-13 11:00:00       C012     B004          NaN
513     M0490  2026-01-25 09:00:00       C010     B004          NaN

     humidite_relative  pression  consommation    etat niveau_temperature
520              53.28   1010.05        195.37  ALERTE             Élevée
447              69.20   1016.10        172.49      OK             Élevée
224              67.98   1020.09        157.99      OK             Élevée
500              52.13   1004.23        262.66      OK             Élevée
9                44.37   1008.27        206.59      OK            Normale
..                 ...       ...           ...     ...                ...
277              71.17   1017.44        293.92      OK            Normale
338              63.37   1004.50        256.18      OK            Normale
487              66.27   1012.49        312.92  ERREUR            Normale
215              59.96   1007.98        294.02      OK            Normale
513              52.97   1010.71        253.63      OK            Normale

[605 rows x 10 columns]

Partie 8 : Analyse 
1) Afficher la consommation moyenne par bâtiment 
2) Afficher le minimum, le maximum, la moyenne et l’écart-type de la température par bâtiment 
3) Afficher, par bâtiment, le maximum et la moyenne de la température et de la consommation 
4) Afficher la température moyenne globale 
5) Afficher la température maximale 
6) Afficher la consommation totale 
7) Quel bâtiment consomme le plus en moyenne ? 
8) Afficher le nombre d'alertes par bâtiment

1.Afficher la consommation moyenne par batiment

In [45]:
print(
    df.groupby("batiment")["consommation"].mean()
)

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64

2. Afficher le minimum, le maximum, la moyenne et l’écart-type de la température par bâtiment

In [46]:
stats_temperature = df.groupby("batiment")["temperature"].agg(
    ["min", "max", "mean", "std"]
)

print(stats_temperature)

            min    max       mean       std
batiment
B001      16.77  32.72  23.578824  2.961211
B002      17.67  33.60  25.778000  2.951828
B003      14.11  31.74  23.013699  2.983902
B004     -18.50  58.70  27.119000  5.367361

3.Afficher, par bâtiment, le maximum et la moyenne de la température et de la consommation

In [47]:
stats_batiment = df.groupby("batiment").agg({
    "temperature": ["max", "mean"],
    "consommation": ["max", "mean"]
})

print(stats_batiment)

         temperature            consommation
                 max       mean          max        mean
batiment
B001           32.72  23.578824       294.72  177.870927
B002           33.60  25.778000       335.20  221.785333
B003           31.74  23.013699       875.00  153.191000
B004           58.70  27.119000       411.12  282.552282

4.Afficher la température moyenne globale

In [48]:
print(df["temperature"].mean())

24.87831385642738

5.Afficher la température maximale

In [49]:
print(df["temperature"].max())

58.7

6.Afficher la consommation totale

In [50]:
print(df["consommation"].sum())

125205.25

7.Quel bâtiment consomme le plus en moyenne ?

In [51]:
consommation_moyenne = df.groupby("batiment")["consommation"].mean()

print(consommation_moyenne.idxmax())

B004

9.Afficher le nombre d'alertes par bâtiment

In [52]:
alertes = df[df["etat"] == "ALERTE"].groupby("batiment").size()

print(alertes)

batiment
B001     2
B002     7
B003     5
B004    15
dtype: int64

Partie 9 : Gestion des valeurs manquantes 
1) Afficher le nombre de valeurs manquantes par colonne 
2) Afficher le nombre total des valeurs manquantes 
3) Afficher le taux de valeurs manquantes 
4) Afficher les lignes contenant des valeurs manquantes 
5) Pour la température et l’humidité, remplacer les valeurs manquantes par les moyennes 
6) Pour la consommation, remplacer les valeurs manquantes par la médiane 
7) Pour "etat", remplacer les valeurs manquantes par "INCONNU"

1.Afficher le nombre de valeurs manquantes par colonne

In [53]:
print(df.isna().sum())

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           6
humidite_relative     5
pression              5
consommation          5
etat                  4
niveau_temperature    0
dtype: int64

2.Afficher le nombre total des valeurs manquantes

In [54]:
print(df.isna().sum().sum())

25

3.Afficher le taux de valeurs manquantes

In [57]:
taux_manquant = df.isna().mean() * 100

print(taux_manquant)

id_mesure             0.000000
date_heure            0.000000
id_capteur            0.000000
batiment              0.000000
temperature           0.991736
humidite_relative     0.826446
pression              0.826446
consommation          0.826446
etat                  0.661157
niveau_temperature    0.000000
dtype: float64

4.Afficher les lignes contenant des valeurs manquantes

In [59]:
lignes_manquantes = df[df.isna().any(axis=1)]

print(lignes_manquantes)

    id_mesure           date_heure id_capteur batiment  temperature  \
14      M0056  2026-01-07 07:00:00       C008     B003        22.33
30      M0073  2026-01-08 00:00:00       C001     B001        23.12
91      M0473  2026-01-24 16:00:00       C005     B002        21.32
128     M0300  2026-01-17 11:00:00       C012     B004        23.32
139     M0345  2026-01-19 08:00:00       C009     B003          NaN
146     M0118  2026-01-09 21:00:00       C010     B004        30.32
149     M0034  2026-01-06 09:00:00       C010     B004        28.91
163     M0019  2026-01-05 18:00:00       C007     B003          NaN
196     M0372  2026-01-20 11:00:00       C012     B004        29.33
215     M0204  2026-01-13 11:00:00       C012     B004          NaN
270     M0334  2026-01-18 21:00:00       C010     B004        29.63
303     M0584  2026-01-29 07:00:00       C008     B003        23.78
307     M0169  2026-01-12 00:00:00       C001     B001        21.86
323     M0391  2026-01-21 06:00:00       C007     B003        21.82
459     M0143  2026-01-10 22:00:00       C011     B004        28.65
476     M0527  2026-01-26 22:00:00       C011     B004        26.16
490     M0227  2026-01-14 10:00:00       C011     B004        25.13
491     M0449  2026-01-23 16:00:00       C005     B002        26.82
511     M0506  2026-01-26 01:00:00       C002     B001        24.04
513     M0490  2026-01-25 09:00:00       C010     B004          NaN
526     M0015  2026-01-05 14:00:00       C003     B001        23.17
536     M0252  2026-01-15 11:00:00       C012     B004        27.01
548     M0572  2026-01-28 19:00:00       C008     B003          NaN
556     M0092  2026-01-08 19:00:00       C008     B003          NaN
572     M0190  2026-01-12 21:00:00       C010     B004        24.24

     humidite_relative  pression  consommation    etat niveau_temperature
14               67.42   1014.41        101.20     NaN            Normale
30               63.97       NaN        186.87      OK            Normale
91               70.43   1021.20        194.76     NaN            Normale
128              55.73       NaN        232.38      OK            Normale
139              66.77   1015.33        216.31      OK            Normale
146                NaN   1015.78        261.68      OK             Élevée
149                NaN   1001.23        234.30      OK            Normale
163              69.97   1014.14        181.07      OK            Normale
196              56.91   1020.02           NaN      OK            Normale
215              59.96   1007.98        294.02      OK            Normale
270              67.70   1016.30        363.68     NaN            Normale
303              64.66       NaN        153.81      OK            Normale
307              51.83       NaN        195.72      OK            Normale
323                NaN   1006.47         98.39      OK            Normale
459              66.88   1001.41           NaN      OK            Normale
476                NaN   1024.21        232.87      OK            Normale
490              85.60   1011.20           NaN  ALERTE            Normale
491              61.99       NaN        215.34      OK            Normale
511              57.10   1014.04           NaN      OK            Normale
513              52.97   1010.71        253.63      OK            Normale
526              79.95   1006.07           NaN      OK            Normale
536                NaN   1018.36        263.13      OK            Normale
548              68.63   1018.58        252.48      OK            Normale
556              79.81   1007.05        113.00      OK            Normale
572              73.55   1018.12        299.91     NaN            Normale

5. Pour la température et l’humidité, remplacer les valeurs manquantes par les moyennes

In [60]:
df["temperature"] = df["temperature"].fillna(
    df["temperature"].mean()
)

6.Pour la consommation, remplacer les valeurs manquantes par la médiane

In [61]:
df["consommation"] = df["consommation"].fillna(
    df["consommation"].median()
)

7.Pour "etat", remplacer les valeurs manquantes par "INCONNU"

In [62]:
df["etat"] = df["etat"].fillna("INCONNU")

In [66]:
print(df["etat"])
print(df["temperature"])
print(df["consommation"])

0      OK
1      OK
2      OK
3      OK
4      OK
       ..
600    OK
601    OK
602    OK
603    OK
604    OK
Name: etat, Length: 605, dtype: str
0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64
0      287.28
1      116.20
2      288.50
3      136.65
4      182.62
        ...
600    282.36
601    357.43
602    152.79
603    170.97
604     44.99
Name: consommation, Length: 605, dtype: float64

Partie 10 : Gestion des doublons 
1) Afficher le nombre de doublons 
2) Afficher les doublons 
3) Supprimer les doublons puis vérifier la suppression

1.Afficher le nombre de doublon

In [67]:
print(df.duplicated().sum())

5

2.Afficher les doublons

In [69]:
print(df[df.duplicated()])

    id_mesure           date_heure id_capteur batiment  temperature  \
183     M0599  2026-01-29 22:00:00       C011     B004        22.02
231     M0026  2026-01-06 01:00:00       C002     B001        22.87
355     M0147  2026-01-11 02:00:00       C003     B001        26.14
538     M0456  2026-01-23 23:00:00       C012     B004        20.68
539     M0302  2026-01-17 13:00:00       C002     B001        22.05

     humidite_relative  pression  consommation etat niveau_temperature
183              68.09   1005.90        227.81   OK            Normale
231              77.99   1010.15        213.19   OK            Normale
355              84.97   1003.59        142.31   OK            Normale
538              72.69   1022.77        309.01   OK            Normale
539              58.26   1007.30        140.42   OK            Normale

3.Supprimer les doublons puis vérifier la suppression

In [70]:
df = df.drop_duplicates()

Partie 11 : Statistiques descriptives 
1) Pour la température, afficher le minimum, le maximum, la moyenne, la mediane, l’écart-type et 
le nombre de valeurs 
2) Pour "etat", afficher le mode et le nombre de mesures par état (OK, ALERTE, ERREUR)

1.Pour la temperature , afficher le minimum , le maximum , la moyenne , la mediane l'écart-type et le nombres de valeurs

In [71]:
print("Minimum :", df["temperature"].min())
print("Maximum :", df["temperature"].max())
print("Moyenne :", df["temperature"].mean())
print("Médiane :", df["temperature"].median())
print("Écart-type :", df["temperature"].std())
print("Nombre de valeurs :", df["temperature"].count())

Minimum : -18.5
Maximum : 58.7
Moyenne : 24.896033138564274
Médiane : 24.87831385642738
Écart-type : 4.048027092193241
Nombre de valeurs : 600

2.Pour "etat", afficher le mode et le nombre de mesures par état (OK, ALERTE, ERREUR)

In [73]:
print(df["etat"].mode())
print(df["etat"].value_counts())

0    OK
Name: etat, dtype: str
etat
OK         562
ALERTE      29
ERREUR       5
INCONNU      4
Name: count, dtype: int64

Partie 12 : Exportation 
1) Exporter le dataframe nettoyé dans exports/donnees_nettoyees.csv 
2) Exporter le dataframe nettoyé dans exports/donnees_nettoyees.json