Partie 1 – Series 
1) Créer une Series contenant 4 températures  
2) Afficher son index 
3) Afficher la 1ère valeur 
4) Afficher la dernière valeur 
5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de 
mesure 12h, 13h, 14h et 15h 
6) Afficher la 1ère et la dernière valeur

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\rokha\miniconda3\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\rokha\miniconda3\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\rokha\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\rokha\miniconda3\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\rokha\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

1.Créer une series contenant 4 temperatures

In [4]:
temperatures = pd.Series([15, 28, 32, 44, 35])
print(temperatures)

0    15
1    28
2    32
3    44
4    35
dtype: int64

2.Afficher son index

In [5]:
print(temperatures.index)

RangeIndex(start=0, stop=5, step=1)

3.Afficher la 1ère valeur

In [6]:
print(temperatures.iloc[0])

15

4.Afficher la dernière valeur

In [7]:
print(temperatures.iloc[-1])

35

Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de 
mesure 12h, 13h, 14h et 15h

In [8]:
temperatures_heures = pd.Series(
    [24.5, 25.3, 26.1, 27.4],
    index=["12h", "13h", "14h", "15h"]
)

print(temperatures_heures)

12h    24.5
13h    25.3
14h    26.1
15h    27.4
dtype: float64

In [9]:
temperatures_heures = pd.Series([24.5, 25.3, 26.1, 27.4])

temperatures_heures.index = ["12h", "13h", "14h", "15h"]

print(temperatures_heures)

12h    24.5
13h    25.3
14h    26.1
15h    27.4
dtype: float64

6.Afficher la 1ère et la dernière valeur

In [10]:
print("Première valeur :", temperatures_heures.iloc[0])
print("Dernière valeur :", temperatures_heures.iloc[-1])

Première valeur : 24.5
Dernière valeur : 27.4

Partie 2 – DataFrame 
1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant 
data = { 
"capteur": ["C001", "C002", "C003"], 
"temperature": [24.5, 25.1, 26.3], 
"humidite": [65, 67, 70] 
} 
2) Importer le dataset mesures_capteurs.csv dans le dataframe df 
3) Afficher les dimensions de df 
NB : dans la suite de l’atelier, on travaillera avec le dataframe df

1.Créer et afficher le dataframe df_test à partir du dictionnaire suivant 
data = { 
"capteur": ["C001", "C002", "C003"], 
"temperature": [24.5, 25.1, 26.3], 
"humidite": [65, 67, 70] }

In [11]:
data = { 
"capteur": ["C001", "C002", "C003"], 
"temperature": [24.5, 25.1, 26.3], 
"humidite": [65, 67, 70] 
}
df_test = pd.DataFrame(data)

print(df_test)

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

2.Importer le dataset mesures_capteurs.csv dans le dataframe df

In [12]:
df = pd.read_csv("../data/mesures_capteurs.csv")

print(df)

    id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0       M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1       M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2       M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3       M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4       M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80
..        ...                  ...        ...      ...          ...       ...
600     M0072  2026-01-07 23:00:00       C012     B004        23.67     60.28
601     M0107  2026-01-09 10:00:00       C011     B004        24.34     61.42
602     M0271  2026-01-16 06:00:00       C007     B003        23.73     63.49
603     M0436  2026-01-23 03:00:00       C004     B002        24.83     79.77
604     M0103  2026-01-09 06:00:00       C007     B003        17.02     52.04

     pression  consommation etat
0     1008.95        287.28   OK
1      993.39        116.20   OK
2     1010.32        288.50   OK
3     1019.62        136.65   OK
4     1016.58        182.62   OK
..        ...           ...  ...
600   1015.11        282.36   OK
601   1019.43        357.43   OK
602   1016.46        152.79   OK
603   1017.05        170.97   OK
604   1001.14         44.99   OK

[605 rows x 9 columns]

3.Afficher les dimensions de df 
NB : dans la suite de l’atelier, on travaillera avec le dataframe df

In [13]:
dimensions = df.shape
print("Dimensions du DataFrame :", dimensions)

Dimensions du DataFrame : (605, 9)

Partie 3 – Exploration 
1) Afficher les premières lignes 
2) Afficher les 10 premières lignes 
3) Afficher les dernières lignes 
4) Afficher le nombre de lignes 
5) Afficher le nombre de colonnes 
6) Afficher les noms des colonnes 
7) Afficher les informations générales 
8) Afficher les statistiques descriptives

1.Afficher les premières lignes

In [14]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

2. Afficher les 10 premières lignes

In [15]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

3.Afficher les dernières lignes

In [16]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

4.Afficher le nombre de lignes

In [24]:
print(df.shape[0])

605

5.Afficher le nombre de colonnes

In [25]:
print(df.shape[1])

9

6.Afficher les noms des colonnes

In [26]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='str')

7.Afficher les informations générales

In [27]:
df.info

<bound method DataFrame.info of     id_mesure           date_heure id_capteur batiment  temperature  humidite  \
0       M0413  2026-01-22 04:00:00       C005     B002        25.46     58.06
1       M0290  2026-01-17 01:00:00       C002     B001        24.00     79.73
2       M0077  2026-01-08 04:00:00       C005     B002        25.82     54.47
3       M0079  2026-01-08 06:00:00       C007     B003        28.23     69.39
4       M0183  2026-01-12 14:00:00       C003     B001        20.58     53.80
..        ...                  ...        ...      ...          ...       ...
600     M0072  2026-01-07 23:00:00       C012     B004        23.67     60.28
601     M0107  2026-01-09 10:00:00       C011     B004        24.34     61.42
602     M0271  2026-01-16 06:00:00       C007     B003        23.73     63.49
603     M0436  2026-01-23 03:00:00       C004     B002        24.83     79.77
604     M0103  2026-01-09 06:00:00       C007     B003        17.02     52.04

     pression  consommation etat
0     1008.95        287.28   OK
1      993.39        116.20   OK
2     1010.32        288.50   OK
3     1019.62        136.65   OK
4     1016.58        182.62   OK
..        ...           ...  ...
600   1015.11        282.36   OK
601   1019.43        357.43   OK
602   1016.46        152.79   OK
603   1017.05        170.97   OK
604   1001.14         44.99   OK

[605 rows x 9 columns]>

8.Afficher les statistiques descriptives

In [28]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

Partie 4 – Sélection  
1) Sélectionner la colonne "temperature" 
2) Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"  
3) Sélectionner les 5 premières lignes avec loc 
4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

1.Selectionner la colonne "temperature"

In [29]:
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

2.Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"

In [30]:
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

3.Sélectionner les 5 premières lignes avec loc

In [31]:
df.loc[:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

4. Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

In [32]:
df.iloc[:5, :4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

Partie 5 – Manipulation des colonnes 
1) Ajouter la colonne "temperature_fahrenheit" 
2) Ajouter la colonne "niveau_temperature" pour catégoriser la température en  
"Élevée" (température
 > 30) ou "Normale". On peut utiliser la méthode where() de numpy 
3) Renommer la colonne "humidite" en "humidite_relative" 
4) Supprimer la colonne "temperature_fahrenheit"